### ISSUE TITLE
[BUG] Safari doesn't display hostname but Chrome does.

### ISSUE THREAD

**Issue by pyrodex** [aceberg/WatchYourLAN#104] opened 2024-08-31 22:17 UTC
I noticed in Safari the hostnames aren't showing but they are in Chrome.

Chrome:
<img width="1304" alt="Screenshot 2024-08-31 at 6 16 31 PM" src="https://github.com/user-attachments/assets/f0ca2b12-56c0-44d1-80cc-333018760cca">
Safari:
<img width="1280" alt="Screenshot 2024-08-31 at 6 16 40 PM" src="https://github.com/user-attachments/assets/fd403a77-9c25-4ea3-8892-aad68a5bf598">

**Comment by SteveClement** [comment] 2024-09-01 10:46
I can confirm the Bug.

The reason is that the <option> tag wants to be inside a <select> Tag.

Maybe @aceberg could tell us why this should be an option list in the first place. Perhaps if you want to have multiple names for one host.

A PR has been done which would fix this #110

**Comment by aceberg** [comment] 2024-09-01 17:39
> I can confirm the Bug.
> 
> The reason is that the tag wants to be inside a Tag. Maybe @aceberg could tell us why this should be an option list in the first place. Perhaps if you want to have multiple names for one host. A PR has been done which would fix this #110

Using option was intended. I needed a tag that has value field inside.
May be, you can suggest something better than option?

**Comment by SteveClement** [comment] 2024-09-02 07:21
> Using option was intended. I needed a tag that has value field inside. May be, you can suggest something better than option?

I asked chatgpt and got this suggestion:

<data id="name2" value="my-amazing-server.my.tld.">my-amazing-server.my.tld.</data>

I tried it in a developer window by changing the HTML, and it seems to work.

**Comment by aceberg** [comment] 2024-09-02 08:01
> > Using option was intended. I needed a tag that has value field inside. May be, you can suggest something better than option?
> 
> I asked chatgpt and got this suggestion:
> 
> `<data id="name2" value="my-amazing-server.my.tld.">my-amazing-server.my.tld.</data>`
> 
> I tried it in a developer window by changing the HTML, and it seems to work.
> 
> @aceberg I amended my PR #110 perhaps you could test if it works as expected.

Yes, it works! Thanks! Will be included in the release in a few days

**Closed** 2024-09-02 14:26 UTC
Labels: bug
